/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package supermarket;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karth
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnumber = new javax.swing.JTextField();
        txtqty = new javax.swing.JPanel();
        txtpname1 = new javax.swing.JLabel();
        txtpname = new javax.swing.JTextField();
        txtqty1 = new javax.swing.JLabel();
        txtprice1 = new javax.swing.JLabel();
        txtprice = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtqty2 = new javax.swing.JTextField();
        txttotal1 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        txtpay1 = new javax.swing.JLabel();
        txtpay = new javax.swing.JTextField();
        txtbalance1 = new javax.swing.JLabel();
        txtbalance = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        btnbill = new javax.swing.JButton();
        txthis = new javax.swing.JButton();

        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 500, 50));

        jLabel3.setText("contact number is not correct");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VISHNU PRIYA SUPER  MARKET");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUSTOMER DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CUSTOMER NAME");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("MOBILE NUMBER");

        txtnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnumberActionPerformed(evt);
            }
        });
        txtnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnumberKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcname, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtnumber))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        txtqty.setBackground(new java.awt.Color(0, 51, 255));
        txtqty.setForeground(new java.awt.Color(255, 255, 255));
        txtqty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtpname1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpname1.setForeground(new java.awt.Color(255, 255, 255));
        txtpname1.setText("PRODUCT NAME");

        txtqty1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtqty1.setForeground(new java.awt.Color(255, 255, 255));
        txtqty1.setText("Qty");

        txtprice1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtprice1.setForeground(new java.awt.Color(255, 255, 255));
        txtprice1.setText("PRICE");

        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpriceKeyPressed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(204, 204, 204));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(255, 0, 102));
        btnadd.setText("ADD ITEMS");
        btnadd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btnaddStateChanged(evt);
            }
        });
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 0));
        jButton2.setText("DELETE ITEM");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtqty2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtqty2ComponentAdded(evt);
            }
        });
        txtqty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqty2ActionPerformed(evt);
            }
        });
        txtqty2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqty2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout txtqtyLayout = new javax.swing.GroupLayout(txtqty);
        txtqty.setLayout(txtqtyLayout);
        txtqtyLayout.setHorizontalGroup(
            txtqtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtqtyLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtpname1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(txtqty1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtqty2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112)
                .addComponent(txtprice1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(txtqtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(btnadd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        txtqtyLayout.setVerticalGroup(
            txtqtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtqtyLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(txtqtyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpname1)
                    .addComponent(txtpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty1)
                    .addComponent(txtprice1)
                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtqty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        txttotal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttotal1.setText("TOTAL");

        txtpay1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpay1.setText("PAY");

        txtpay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpayKeyPressed(evt);
            }
        });

        txtbalance1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtbalance1.setText("BALANCE");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductName", "Qty", "Price", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        txtbill.setColumns(20);
        txtbill.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtbill.setRows(5);
        jScrollPane2.setViewportView(txtbill);

        btnbill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbill.setText("INVOICE");
        btnbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbillActionPerformed(evt);
            }
        });
        btnbill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnbillKeyPressed(evt);
            }
        });

        txthis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txthis.setText("BILL HISTORY");
        txthis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(txthis)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtqty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtpay1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(txttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtpay, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(txttotal)
                                            .addComponent(txtbalance, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnbill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(54, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txthis, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txttotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpay1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtpay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtbalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtbalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnbill, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

      //  DefaultTableModel tblModel1 = (DefaultTableModel) jTable1.getModel();
         DefaultTableModel tblModel1 = (DefaultTableModel) jTable1.getModel();
        
        if(jTable1.getSelectedRowCount()==1)
        {
            tblModel1.removeRow(jTable1.getSelectedRow());
        }
        else
        {
            if(jTable1.getRowCount()==0)
            {
                JOptionPane.showMessageDialog(this , "table is empty.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "please select any row for delete.");
            }
        }
        int sum=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(jTable1.getValueAt(i,3).toString());
            
        }
        txttotal.setText(Integer.toString(sum));
  
    }//GEN-LAST:event_jButton2ActionPerformed

     public void Balance()
     {
         int totally = Integer.parseInt(txttotal.getText());
         int pays = Integer.parseInt(txtpay.getText());
         int bal = pays-totally;
         txtbalance.setText(String.valueOf(bal));
     }
    
    public void bill()
    {
           String total = txttotal.getText();
           String pay = txtpay.getText();
           String bal = txtbalance.getText();
           String cname = txtcname.getText();
           String pnumber = txtnumber.getText();
         //  String date = txtfix.getText();
          // SimpleDateFormat dFormat = new SimpleDateFormat("DD-MM-yyyy");
           
        //   String date = Ingeter.toString(txtdate.getText());
           // txttotal.setText(Integer.toString(sum));


           DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
           
           txtbill.setText(txtbill.getText() + "**************************************************************************************************************\n");
           txtbill.setText(txtbill.getText() + "        **********************VISHNU PRIYA SUPERMARKET BILL************************** \n");
           txtbill.setText(txtbill.getText() + "**************************************************************************************************************\n");
           Date obj = new Date();
           String date =obj.toString();
           txtbill.setText(txtbill.getText()+ "DATE AND TIME :"+ date +"\n");
           
           txtbill.setText(txtbill.getText() +"CUSTOMER NAME :"+ cname+ "\n");
           txtbill.setText(txtbill.getText() +"CONTACT NUMBER :" +pnumber+ "\n");
          // txtbill.append(txtdate.getText() +"\n");


           txtbill.setText(txtbill.getText() +             "PRODUCTNAME" + "\t" + "QTY"+ "\t" + "PRICE" + "\t" + "AMOUNT" + "\n");
           
           
           for(int i=0;i<tblModel.getRowCount();i++)
           {
               String pname = (String)tblModel.getValueAt(i,0);
               String qty = (String)tblModel.getValueAt(i,1);
               String price = (String)tblModel.getValueAt(i,2);
               String amount = (String)tblModel.getValueAt(i,3);
               txtbill.setText(txtbill.getText() +  pname +  "\t"+ "\t" + qty + "\t" + price + "\t" + amount + "\n");
           }
           txtbill.setText(txtbill.getText()+"\n");
           txtbill.setText(txtbill.getText()+"\n");
           
           txtbill.setText(txtbill.getText()+ "\t" +"\t" + "SUBTOTAL :" + total + "\n");
           txtbill.setText(txtbill.getText()+ "\t" +"\t" + "PAY      :" + pay + "\n");
           txtbill.setText(txtbill.getText()+ "\t" +"\t" + "BALANCE  :" + bal + "\n");
           txtbill.setText(txtbill.getText()+"\n");
           txtbill.setText(txtbill.getText() + "**************************************************************************************************************\n");
           txtbill.setText(txtbill.getText() + "                                  THANK YOU VISIT AGAIN \n");
           txtbill.setText(txtbill.getText() + "**************************************************************************************************************\n");
             
           
    }
    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:

        if(txtpname.getText().equals("") || txtqty2.getText().equals("") || txtprice.getText().equals("") || txtnumber.getText().length()<10)
       
        {
            if(txtnumber.getText().length()<10)
            {
                JOptionPane.showMessageDialog(this, "contact number is not correct");
            }
            else
            {
                           JOptionPane.showMessageDialog(this, "Please Enter All The Data");
 
            }
        }
        else
        {
            //store enter the data into the table
             int qtys = Integer.parseInt(txtqty2.getText());
             int amounts = Integer.parseInt(txtprice.getText());
              int totals = qtys*amounts;
             // String cname = txtcname.getText();
              
            //  System.out.println(Integer.toString(totals));
        
  
            String data[] = {txtpname.getText(),txtqty2.getText(),txtprice.getText(),Integer.toString(totals)};

            DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
            tblModel.addRow(data);
            txtpname.setText("");
            txtqty2.setText("");
            txtprice.setText("");
        }

        int sum=0;
        for(int i=0;i<jTable1.getRowCount();i++)
        {
            sum=sum+Integer.parseInt(jTable1.getValueAt(i,3).toString());
            txttotal.setText(Integer.toString(sum));
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void txtqty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqty2ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txtqty2ActionPerformed

    private void txtqty2ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtqty2ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqty2ComponentAdded

    private void btnaddStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btnaddStateChanged
       
 
    }//GEN-LAST:event_btnaddStateChanged

    /**
     *
     * @param datarow
     */
 //  Connection cnl;
 //  PreparedStatement insert;
   public void harsh()
   {
       String name = txtcname.getText();
     //  String date = txtdate.getText();
        String number = txtnumber.getText();
       String total = txttotal.getText();
        Date obj = new Date();
        String dateS =obj.toString();
      PreparedStatement insert;

       try {
            // TODO add your handling code here:
            Class.forName("com.mysql.cj.jdbc.Driver");
          System.out.println("hekki");
        Connection cnl = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/billhistory","root",""); 
      //  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

        insert = cnl.prepareStatement("CREATE DATABASE IF NOT EXISTS NAMEDETAIL"); 
        insert.executeUpdate();
        insert=cnl.prepareStatement("USE NAMEDETAIL");
        insert.executeUpdate();
        insert = cnl.prepareStatement("CREATE TABLE IF NOT EXISTS HISTORYS(NAME VARCHAR(20),DATES VARCHAR(220),NUMBER VARCHAR(30),TOTAL VARCHAR(20))"); 
        insert.executeUpdate();
        insert = cnl.prepareStatement("insert into historys values('"+name + "','"+dateS+"','"+number+"','"+total+"')");
                insert.executeUpdate();
        
        
                 JOptionPane.showMessageDialog(this, "hello venu");
  // insert.cnl=prepareStatement("select * from historys")
                               
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
        }             
   }
   
    private void btnbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbillActionPerformed
        // TODO add your handling code here:
        
        Balance();
        bill();  
             
     harsh();
       txtcname.setText("");
        txtnumber.setText("");
        txttotal.setText("");
        txtpay.setText("");
        txtbalance.setText("");
      //  txtdate.setText("");

    }//GEN-LAST:event_btnbillActionPerformed

    private void txtnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumberKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtnumber.setEditable(false);
        }
        else
        {
            txtnumber.setEditable(true);
        }
    }//GEN-LAST:event_txtnumberKeyPressed

    private void txtqty2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqty2KeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtqty2.setEditable(false);
        }
        else
        {
            txtqty2.setEditable(true);
        }
    }//GEN-LAST:event_txtqty2KeyPressed

    private void txtpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtprice.setEditable(false);
        }
        else
        {
            txtprice.setEditable(true);
        }
    }//GEN-LAST:event_txtpriceKeyPressed

    private void txtpayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpayKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(Character.isLetter(c))
        {
            txtpay.setEditable(false);
        }
        else
        {
            txtpay.setEditable(true);
        }
    }//GEN-LAST:event_txtpayKeyPressed

    private void txthisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthisActionPerformed
        // TODO add your handling code here:
      BillHistory history = new BillHistory();
      history.setVisible(true);
      history.pack();
      history.setLocationRelativeTo(null);
      history.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
      
    }//GEN-LAST:event_txthisActionPerformed

    private void btnbillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnbillKeyPressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnbillKeyPressed

    private void txtnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnumberActionPerformed
        // TODO add your handling code here:
       // String number = txtnumber.getText();
        
        
    }//GEN-LAST:event_txtnumberActionPerformed
   
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    public static javax.swing.JButton btnbill;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbalance;
    private javax.swing.JLabel txtbalance1;
    private javax.swing.JTextArea txtbill;
    public static javax.swing.JTextField txtcname;
    private javax.swing.JButton txthis;
    private javax.swing.JTextField txtnumber;
    private javax.swing.JTextField txtpay;
    private javax.swing.JLabel txtpay1;
    public javax.swing.JTextField txtpname;
    private javax.swing.JLabel txtpname1;
    private javax.swing.JTextField txtprice;
    private javax.swing.JLabel txtprice1;
    private javax.swing.JPanel txtqty;
    private javax.swing.JLabel txtqty1;
    private javax.swing.JTextField txtqty2;
    private javax.swing.JTextField txttotal;
    private javax.swing.JLabel txttotal1;
    // End of variables declaration//GEN-END:variables

    private void AddRowToTable() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void Statement(String insert_into_historysnamedatenumbervalues) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   


       
}
